linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - prealloc
    - nakedret
    - copyloopvar
    - gocritic
    - shadow        

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
        confidence: 0.8
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3