linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - prealloc
    - nakedret
    - exportloopref
    - gocritic

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3 