name: Build and Test Pipeline

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

env:
  MIN_COVERAGE: 80
  GO_VERSION: "1.20"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go mod tidy

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: go test -v ./...

    - name: Check code coverage
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}' > coverage_percent.txt
        COVERAGE=$(cat coverage_percent.txt)
        if ! command -v bc &> /dev/null; then
          echo "bc command not found, installing..."
          sudo apt-get update && sudo apt-get install -y bc
        fi
        if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
          echo -e "\033[0;31mCode coverage is below $MIN_COVERAGE%: $COVERAGE%\033[0m"
          exit 1
        else
          echo -e "\033[0;32mCode coverage is sufficient: $COVERAGE%\033[0m"
        fi

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go binary
      run: go build -o myapp .