name: Build and Test Pipeline

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

env:
  MIN_COVERAGE: 80

jobs:
  building-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
      # uses: actions/setup-go@v3
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go mod tidy

    - name: Run unit tests
      run: go test -v ./...

    - name: Check code coverage
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}' > coverage_percent.txt
        COVERAGE=$(cat coverage_percent.txt)
        if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
          echo "Code coverage is below $MIN_COVERAGE%: $COVERAGE%"
          exit 1
        else
          echo "Code coverage is sufficient: $COVERAGE%"
        fi

    - name: Build Go binary
      run: go build -o myapp .