name: Go Build Pipeline

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go binary
      run: go build -o myapp .