name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*

env:
  GO_VERSION: '1.20'
  MIN_COVERAGE: 80

jobs:
  lint:
    uses: ./.github/workflows/linting.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  test-build:
    uses: ./.github/workflows/build-test.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  summary:
    runs-on: ubuntu-latest
    needs: [lint, test-build]
    steps:
      - name: Generate summary
        run: |
          echo "\033[0;32mLinting, testing, and building completed successfully!"