name: Go Coverage Report

on:
  push:
    branches:
      - main  
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop  
      - feature/*

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  

      - name: Run tests and generate coverage report
        run: |
          go test -coverprofile=coverage.out ./...

      - name: Generate coverage badge
        uses: axllent/go-coverage-report@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badge: true
          coverage-file: coverage.out