name: Go Linting

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  lint:
    uses: ./.github/workflows/setup-env.yml
    with:
      go-version: ${{ inputs.go-version }}

  linting:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.63.4
        working-directory: ./hello-world-go