name: Go Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Using a stable version
          cache: true

      - name: Clean Go module
        run: |
          rm -f go.mod go.sum || true

      - name: Initialize Go module
        run: |
          go mod init github.com/Obaid-Ghafoori/hello-world-go
          go mod tidy

      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Run go vet
        run: go vet ./...

      - name: Format code
        run: |
          gofmt -w .
          # Check if any files were modified by gofmt
          git diff --exit-code || (echo "Code formatting issues found. Please run 'go fmt ./...'" && exit 1)

      - name: Install and run revive
        run: |
          go install github.com/mgechev/revive@latest
          revive ./...