name: Go Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Using a stable version
          cache: true

      - name: Initialize Go module
        run: |
          go mod init github.com/Obaid-Ghafoori/hello-world-go || true
          go mod tidy

      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Run go vet
        run: go vet ./...

      - name: Check code formatting
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Install and run revive
        run: |
          go install github.com/mgechev/revive@latest
          revive ./...