name: Go Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
          cache: true

      - name: Initialize Go module
        run: |
          go mod init github.com/Obaid-Ghafoori/hello-world-go || true
          go mod tidy

      - name: Install staticcheck
        run: |
          GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          go install honnef.co/go/tools/cmd/staticcheck@v0.4.6

      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          staticcheck -version
          staticcheck ./...

      - name: Check code formatting
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi